# TODO: not used
version: "3"
services:
  database:
    image: "postgres"
    env_file:
      - ./config/database.env
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
