server:
  port: 8000
  error:
    include-message: always

logging:
  level:
    root: DEBUG

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8100/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # https://medium.com/swlh/using-correlation-ids-with-spring-cloud-gateway-and-eureka-f00145c579ab
          enabled: true

##### Custom properties
base-path: /api/v1
