# Please modify the following 2 properties as required
# TODO pass values from environment variables
directory: ~/music
library: ~/music/music_library.db
import:
  move: no
  copy: yes
plugins: fetchart lyrics lastgenre scrub inline web
per_disc_numbering: yes
paths:
    default: $albumartist/[$year] $album%aunique{}/%if{$multidisc,$disc-}$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/[$year] $album%aunique{}/%if{$multidisc,$disc-}$track $title
item_fields:
  multidisc: 1 if disctotal > 1 else 0
lastgenre:
  count: 5
